# Variables to be configured during pipeline creation/execution
# groupId
# environment
# location
# resourceGroupName
# azureServiceConnectionName

trigger:
 branches:
   include:
     - main
 paths:
   include:
     - /deployment/azure/logic-apps/*

stages:
- stage: Deployment
  jobs:
  - job: AzureResourceDeployment
    pool: 
      vmImage: 'ubuntu-18.04'
    steps:
    - template: ../../pipelines/templates/deploy-azure.yml
      parameters: 
        name: DeployWorkOrderCreateLogicApp
        deploymentMode: Incremental
        ARMTemplateFile: $(Build.Repository.LocalPath)/deployment/azure/logic-apps/work-order-create/azure-deploy.json
        ARMParametersFile: $(Build.Repository.LocalPath)/deployment/azure/logic-apps/work-order-create/azure-deploy-parameters-$(environment).json
    - template: ../../pipelines/templates/deploy-azure.yml
      parameters: 
        name: DeployWorkOrderAckLogicApp
        deploymentMode: Incremental
        ARMTemplateFile: $(Build.Repository.LocalPath)/deployment/azure/logic-apps/work-order-ack/azure-deploy.json
        ARMParametersFile: $(Build.Repository.LocalPath)/deployment/azure/logic-apps/work-order-ack/azure-deploy-parameters-$(environment).json
